version: '3'
services:
  bamp:
    image: bamp
    build: .
    environment: 
      - PULSE_SERVER=127.0.0.1
    volumes:
      - "~/.config/pulse:/var/lib/mopidy/.config/pulse"
      - "../mopidy_bamp:/var/lib/mopidy/mopidy_bamp"
      - "../database:/var/lib/mopidy/database"
      - "../media:/var/lib/mopidy/media"
    networks:
      - bamp-network
    ports:
      - "6680:6680"
  openldap: 
    image: osixia/openldap:1.2.2
    ports:
      - "389:389"
      - "636:636"
    networks:
      - bamp-network
  ldap-admin:
    image: osixia/phpldapadmin:0.7.2
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "44304:443"
    networks:
      - bamp-network
networks:
  bamp-network: